### PR TITLE
Feat: member register,login

### PR DESCRIPTION
**Pull request by SweiiHuang**
Discord : Swei#9006

Feat: member register, login

http://18.178.97.253:3000/
http://18.178.97.253:3000/attraction/12

Thank you.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Don't show popup sign in/up dialog when we click sign out text.

**Comment by SweiiHuang** [comment]
Dear teacher,
The popup sign in/up dialog has been cancelled.
Thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I still see popup sign in/up dialog when clicking sign out text.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by SweiiHuang** [comment]
Thank you.

**Pull request merged**
